// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	endpoint "golangmicroservices/accounts/pkg/endpoint"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeSignUpHandler(m, endpoints, options["SignUp"])
	makeSignInHandler(m, endpoints, options["SignIn"])
	makeLogoutHandler(m, endpoints, options["Logout"])
	makeUpdateHandler(m, endpoints, options["Update"])
	makeDeleteHandler(m, endpoints, options["Delete"])
	makeMeHandler(m, endpoints, options["Me"])
	makeGetHandler(m, endpoints, options["Get"])
	makeGetUserInfoHandler(m, endpoints, options["GetUserInfo"])
	makeAddFundsHandler(m, endpoints, options["AddFunds"])
	return m
}
