// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	endpoint "golangmicroservices/transactions/pkg/endpoint"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeCreateHandler(m, endpoints, options["Create"])
	makeAcceptHandler(m, endpoints, options["Accept"])
	makeRejectHandler(m, endpoints, options["Reject"])
	makeGetAllHandler(m, endpoints, options["GetAll"])
	return m
}
